INPUT_FILE=$1
OUTPUT_FILE=$2
G4PRODUCER="largeant"

RUN=1
MIN_EVENT=452
MAX_EVENT=1452
MIN_CHANNEL=$3
MAX_CHANNEL=$4

if [ -z "$4" ]
then
    MAX_CHANNEL=$3
fi

make all
./GetSimChan "$INPUT_FILE" "$OUTPUT_FILE" "$G4PRODUCER" "$RUN" "$MIN_EVENT" "$MAX_EVENT" "$MIN_CHANNEL" "$MAX_CHANNEL"

rm GetSimChan
